### ISSUE TITLE
What is a image spool?

### ISSUE THREAD

**Issue by spto** [jah1994/TheThresher#1]
Hi,

What is an image spool? Do you mean .fits file can hold multiple frames in a single file?

Is there any recommendation on what tool should I use to compile multiple frames in a single fits that this pipeline can handle? Currently, I'm using PIPP to preprocess the image series and generating .ser files for lucky imaging processing.

btw, what is init_path and what are the different roles they are playing? They seems both are .fits files.

Cheers
Boyang

**Comment by jah1994** [comment]
Hi Boyang,

_>>What is an image spool? Do you mean .fits file can hold multiple frames in a single file?_
Yes, an image “spool” is a .fits file holding many frames. The Thresher expects the spool to have dimensions: (Number of images in the spool, image width, image height).

_>>Is there any recommendation on what tool should I use to compile multiple frames in a single fits that this pipeline can handle? Currently, I'm using PIPP to preprocess the image series and generating .ser files for lucky imaging processing._
I’m not aware of anything in particular. In the past I’ve just created a 3D numpy array of the imaging data with the above dimensions, which can then be saved as a .fits using astropy.io.fits with a function like the following...

def save_numpy_as_fits(numpy_array, filename):
    ‘’’
    numpy_array (numpy.ndarray): the array of imaging data
    filename (string): the name of the .fits file to save
    ‘’’
    hdu = fits.PrimaryHDU(numpy_array)
    hdul = fits.HDUList([hdu])
    hdul.writeto(filename, overwrite=True)

_>>btw, what is init_path and what are the different roles they are playing? They seems both are .fits files._
Yeah, init_path is the path to the .fits file that’s used to initialise the “scene” model. This is a **single** image, and could be e.g. the coadd of the best images in your data set. I usually just take the per-pixel mean of the best 50% of images so that the photometric scale of the model is comparable to the data. And I’d strongly recommend subtracting some estimate of the background “sky” level from this image too so that the background level is close to 0, as otherwise some numerical problems can arise.

Hope that helps,
James

**Comment by spto** [comment]
Thanks for the explanation! I'll try the pipeline on my data asap.

**Comment by jah1994** [comment]
Don't hesitate to ask if you have any more questions :)

Optimisation problems can be "delicate".

**Comment by spto** [comment]
Thank you! Can the program handle RGB images? So the spool has dimensions (Number of images in the spool, colors, image width, image height).

**Comment by spto** [comment]
I tried both RGB images and monochrome images. Both get the following error:

PyTorch version: 1.11.0
GPU not found, defaulting to CPU (not tested!)...
Subtracting median pixel value from the scene initialisation
Image 1/3000
Number of updates: 0
/Users/boyangliu/opt/anaconda3/lib/python3.8/site-packages/skimage/feature/__init__.py:43: skimage_deprecation: Function ``register_translation`` is deprecated and will be removed in version 0.19. Use ``skimage.registration.phase_cross_correlation`` instead.
  removed_version='0.19')
Traceback (most recent call last):
  File ".../TheThresher-main/thresh.py", line 81, in <module>
    y = utils.align(s0, y) # integer align
  File ".../TheThresher-main/utils.py", line 28, in align
    shifts, error, diffphase = register_translation(template, data)
  File "/Users/boyangliu/opt/anaconda3/lib/python3.8/site-packages/skimage/_shared/utils.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/Users/boyangliu/opt/anaconda3/lib/python3.8/site-packages/skimage/feature/__init__.py", line 47, in register_translation
    return phase_cross_correlation(src_image, target_image,
  File "/Users/boyangliu/opt/anaconda3/lib/python3.8/site-packages/skimage/registration/_phase_cross_correlation.py", line 196, in phase_cross_correlation
    raise ValueError("images must be same shape")
ValueError: images must be same shape

Do you know why is that? All my images in the spool are same size of 300x300.

**Comment by jah1994** [comment]
This is probably because the image used for initialising the scene model has a different width and height to the given data image. The Thresher expects the model to be the same size as the images in the spool (so all data images must have the same width and height too).

Here, the pipeline has grabbed the given data image from the .fits spool (the first image in this case) and is attempting to align it to the model image by some integer number of pixels. This alignment is done to guard against the inferred kernel/PSF that “maps” the model to this bit of data having too much off-centre power which falls outside the size of the square kernel object. This is set by the “kernel_size” parameter in the config file; default value is 25 x 25 pixels, but you can make this larger or smaller if you need by checking some of the output “Convolution Kernel” panels in the output progress plots, which are saved at a rate determined by “plot_freq”. Larger kernels can capture more variation, but computations slow down. Rule-of-thumb is to set it to something roughly the size of the PSF of the data.

Also, I note that the pipeline is expecting there to be 3000 images in the spool. This is the default value in the config file, so make sure this is right for your problem. This needs to be specified since we never load the entire spool into memory - we just access one image at a time.

And to your previous question, the pipeline’s designed to only work with single band data, so will fail if you try and feed it RGB images. And I’m guessing your data isn’t from an EMCCD? So in the config file make sure EMCCD = False and CCD = True, and try and provide some reasonable values for the readout noise and gain if you can (“sigma” and “gain” respectively).

Finally, I note you don’t have a cuda enabled GPU. This shouldn’t affect the results, but it will run slow. How big are your images?

**Comment by jah1994** [comment]
*How big are your images?

Ah, sorry I see you've mentioned they're 300x300. OK that isn't that large so performance won't be too painful on the CPU
